/* DO NOT EDIT THIS FILE - it is machine generated */
#include <jni.h>
/* Header for class jni_HelloNative */

#ifndef _Included_jni_HelloNative
#define _Included_jni_HelloNative
#ifdef __cplusplus
extern "C" {
#endif
/*
 * Class:     jni_HelloNative
 * Method:    greeting
 * Signature: (I)Ljava/lang/String;
 */
JNIEXPORT jstring JNICALL Java_jni_HelloNative_getString__I
  (JNIEnv *, jobject, jint);

/*
 * Class:     jni_HelloNative
 * Method:    greeting
 * Signature: ()Ljava/lang/String;
 */
JNIEXPORT jstring JNICALL Java_jni_HelloNative_getString__
  (JNIEnv *, jobject);

#ifdef __cplusplus
}
#endif
#endif
